AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  WAAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        ApiKeyRequired: true

  HelloFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.hello
      Runtime: nodejs12.x
      CodeUri: ./hello
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref WAAPI
            Path: /hello
            Method: GET

  ApiKey:
    Type: 'AWS::ApiGateway::ApiKey'
    DependsOn:
      - "UsagePlan"
    Properties:
      Name: WA-API-KEY
      Description: API Key demo
      Enabled: 'true'
      StageKeys:
        - RestApiId: !Ref WAAPI
          StageName: dev

  UsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    DependsOn:
      - WAAPIdevStage
    Properties:
      ApiStages:
        - ApiId: !Ref WAAPI
          Stage: dev
      Description: WA API Gateway Usage Plan
      Quota:
        Limit: 5
        Period: DAY
      Throttle:
        BurstLimit: 2
        RateLimit: 1
      UsagePlanName: WA-User-Plan

  UsagePlanKey:
    Type: 'AWS::ApiGateway::UsagePlanKey'
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  ApiId:
    Description: "API ID"
    Value: !Ref WAAPI

  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub 'https://${WAAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/'